export enum ProjectStatus {
  DEVELOPMENT = 'DEVELOPMENT',
  PRE_PRODUCTION = 'PRE PRODUCTION',
  PRODUCTION = 'PRODUCTION',
  POST_PRODUCTION = 'POST PRODUCTION',
  FILM_FESTIVALS = 'FILM FESTIVALS',
  MEDIA_PLAN = 'MEDIA PLAN',
  DISTRIBUTION = 'DISTRIBUTION',
  FILM_BUDGET = 'FILM BUDGET',
}

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
